Change travis CI configuration for ruby 2.2
  rubygems in ruby 2.2 seems to query dependencies from remote gemspec
and local one for current gem, leading to conflicts:

  ERROR:  While executing gem ... (Gem::DependencyResolutionError)
      conflicting dependencies uh (= 2.0.2) and uh (= 2.0.3)
    Activated uh-2.0.3
    which does not match conflicting dependency (= 2.0.2)

    Conflicting dependency chains:
      uh (= 2.0.3), 2.0.3 activated

    versus:
      uh-wm (= 0.0.15), 0.0.15 activated, depends on
      uh (= 2.0.2)